### ISSUE TITLE
Blockchain and Wallet Replacement and Replication

### ISSUE THREAD

**Issue by abhisachdev17** [ZackHolmberg/COMP4350-Project#129]
As a part of the Sprint 2 evaluation, TA added this requirement that our application should support.
Currently, the Blockchain is a single point of failure as it is one node that handles chains and wallets. we want to add persistence to this node, storing in the database is not optimal as the chain should be distributed.
This will require further investigation on adding P2P and consensus for blockchain nodes.

**Comment by ZackHolmberg** [comment]
Investigation results:

We will move forward with Kubernetes as the solution for this problem:

[What  is kubernetes](https://kubernetes.io/docs/concepts/overview/what-is-kubernetes/#why-you-need-kubernetes-and-what-can-it-do)

[Kubernetes replication solution](https://kubernetes.io/docs/concepts/workloads/controllers/replicationcontroller/)

[Kubernetes replication solution 2](https://www.stratoscale.com/blog/kubernetes/manage-pods-replication-controllers-kubernetes/)
