### ISSUE TITLE
Create MongoDB service

### ISSUE THREAD

**Issue by akshaysharma21** [ZackHolmberg/COMP4350-Project#43]
**Description:**
- Initialize MongoDB service with root and user accounts for access.
- Create user collection with name and privateKey fields.
- Create sample persistent data.

**Comment by ZackHolmberg** [comment]
@akshaysharma21 Due to the direction shift this can either be deleted or moved into sprint 3 when we implement user accounts! But all key-related stuff is no-longer needed
