### ISSUE TITLE
Participate In Mining

### ISSUE THREAD

**Issue by madisonfines** [ZackHolmberg/COMP4350-Project#57]
**Description:** 
Students will be able to act as miners on the blockchain network, earning BisonCoin as a reward.

**Related User Stories:**

- [x] #10 As a student, I want to be able to join the mining network so that I can earn rewards by mining blocks.
- [x] #61 As a student, I want to be able to leave the mining network so that I can stop my device from mining.

**Comment by abhisachdev17** [comment]
Can we close this issue?
