### ISSUE TITLE
View Wallet And Transaction History

### ISSUE THREAD

**Issue by madisonfines** [ZackHolmberg/COMP4350-Project#58]
**Description:**
Students will be able to view how much BisonCoin they obtain in their digital wallet, as well as view their transaction history.

**Related User Stories:**

- [x] #64 As a student, I want to view my wallet so that I can see how much BisonCoin I have.
- [x] #65 As a student, I want to view my transaction history so that I can view details about my previous transactions.

**Comment by abhisachdev17** [comment]
can we close this now?
