### ISSUE TITLE
Fix the verification bug

### ISSUE THREAD

**Issue by abhisachdev17** [ZackHolmberg/COMP4350-Project#82]
The transaction should not go through when not enough money in the wallet

Description: 
- The transactions were going through when there was not enough money in the wallet, ideally, this should be taken care of in the transaction verification process in the transaction service. Check the transaction verification for issues

Recreation Steps
- Start the services and the frontend, login and create a transactions
-  Send money after you have 0 bison coin left
- the amount goes in negative

**Comment by ZackHolmberg** [comment]
Can you add bug description and recreation steps if possible please
